# Generated by Django 2.2.14 on 2020-08-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_experience_qualifcation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualifcation',
            new_name='Qualification',
        ),
    ]
