# Generated by Django 2.2.14 on 2020-08-21 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200821_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 10, 42, 50, 290537, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='experience',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 10, 42, 50, 290528, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qualification',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 10, 42, 50, 290365, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='qualification',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 10, 42, 50, 290352, tzinfo=utc)),
        ),
    ]
