# Generated by Django 2.2.14 on 2020-08-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200821_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='startDate',
            field=models.DateField(),
        ),
    ]
